version: '3.8'

services:
  app:
    build: .
    container_name: flask_car_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: flask_car_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
